image:  
  repository: bgants/sensor-service
  name: sensor-service
  pullPolicy: Always

replicaCount: 1

serviceAccount:
  name: default

probes:
  liveness:
    type: tcpSocket
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 10
    timeoutSeconds: 1
  readiness:
    type: tcpSocket
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 10
    timeoutSeconds: 1

service:
  type: ClusterIP
  name: sensor-service
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
   - host: localhost 
     paths:
        - /api/sensor/add
        - /api/sensor
