{{- define "common.service" -}}                                                                                                                                                                        
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}  
{{- if .Values.service.clusterIP }}
  clusterIP : {{ .Values.service.clusterIP }}
{{- end }}
  ports: 
    {{ include "common.service.ports" . | nindent 4 }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
{{- end -}}
{{- end -}}
