image:
  repository: bgants/activemq
  name: activemq
  pullPolicy: Always

replicaCount: 1

serviceAccount:
  name: default

service:
  type: ClusterIP
  name: activemq
  port: 61616
  extraPorts:
    - name: nio
      port: 8161

ingress:
  enabled: false
